### ISSUE TITLE
How to construct the provenance graph?

### ISSUE THREAD

**Issue by kunzeng-ch** [hwwzrzr/APT-KGL#3]
Hello! I would like to know what data you use to build the provenance graph and how to construct the provenance graph. Can you elaborate? Can you upload a copy of the sample raw data of the provenance graph?

**Comment by anshen666** [comment]
你好能不能留个联系方式，一起交流一下这个项目呢，万分感谢！微信或者QQ都可以的！

**Comment by anshen666** [comment]
我的微：lovedaixiaobaby

**Comment by hwwzrzr** [comment]
The source data I used included our own Linux system log data and DARPA data sets. The collected Linux system log data is located in the 1.json file in the experiment_data directory. I constructed the Provenance Graph included graph_v4, v5 and v7 through 1.json.

**Comment by hwwzrzr** [comment]
> The source data I used included our own Linux system log data and DARPA data sets. The collected Linux system log data is located in the 1.json file in the experiment_data directory. I constructed the Provenance Graph included graph_v4, v5 and v7 through 1.json.

**Comment by hwwzrzr** [comment]
> 你好能不能留个联系方式，一起交流一下这个项目呢，万分感谢！微信或者QQ都可以的！

好的

**Comment by hwwzrzr** [comment]
> Hello! I would like to know what data you use to build the provenance graph and how to construct the provenance graph. Can you elaborate? Can you upload a copy of the sample raw data of the provenance graph?

The source data I used included our own Linux system log data and DARPA data sets. The collected Linux system log data is located in the 1.json file in the experiment_data directory. I constructed the Provenance Graph included graph_v4, v5 and v7 through 1.json.
